In [41]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [42]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [43]:
df.shape

(569, 33)

In [44]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [45]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [47]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [48]:
X_train

array([[ 0.29213223, -0.67883758,  0.32893932, ...,  0.40963875,
        -0.5380197 , -0.34815713],
       [-0.21129781,  2.81982483, -0.23193796, ..., -0.58503531,
        -1.18864158, -0.40463627],
       [-1.27230588,  2.20456807, -1.27659307, ..., -1.03061606,
        -0.98222601, -0.65662013],
       ...,
       [-1.12449648, -1.69694101, -1.10417838, ..., -0.74914807,
         0.03498993, -0.37911205],
       [-0.11470949,  0.40518623, -0.06841936, ...,  0.61420292,
         0.462683  ,  1.67803199],
       [-0.34886299, -0.69348655, -0.39333844, ..., -0.5124381 ,
         0.17865517, -0.79890411]])

In [49]:
y_train

128    B
455    B
459    B
484    B
374    B
      ..
234    B
199    M
390    B
7      M
195    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [50]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [51]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,

### Numpy arrays to PyTorch tensors

In [52]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [53]:
X_train_tensor.shape

torch.Size([455, 30])

In [54]:
y_train_tensor.shape

torch.Size([455])

In [55]:
X_train_tensor = torch.from_numpy(X_train).float()

### Defining the model

In [56]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  #   # Calculate loss
  #   loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
  #   return loss





### Important Parameters

In [57]:
learning_rate = 0.1
epochs = 25

In [58]:
loss_function = nn.BCELoss()

In [59]:
type(loss_function)

torch.nn.modules.loss.BCELoss

### Training Pipeline

In [60]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.float().view(-1,1))

  # backward pass
  loss.backward()

  # parameters update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad
  optimizer.step()

  # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  optimizer.zero_grad()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6722017526626587
Epoch: 2, Loss: 0.5155371427536011
Epoch: 3, Loss: 0.4332740902900696
Epoch: 4, Loss: 0.38217705488204956
Epoch: 5, Loss: 0.3467045724391937
Epoch: 6, Loss: 0.3202608525753021
Epoch: 7, Loss: 0.29955998063087463
Epoch: 8, Loss: 0.28276965022087097
Epoch: 9, Loss: 0.2687811553478241
Epoch: 10, Loss: 0.25688114762306213
Epoch: 11, Loss: 0.2465878427028656
Epoch: 12, Loss: 0.2375631034374237
Epoch: 13, Loss: 0.2295617014169693
Epoch: 14, Loss: 0.22240105271339417
Epoch: 15, Loss: 0.21594195067882538
Epoch: 16, Loss: 0.21007613837718964
Epoch: 17, Loss: 0.20471793413162231
Epoch: 18, Loss: 0.19979843497276306
Epoch: 19, Loss: 0.19526146352291107
Epoch: 20, Loss: 0.1910606026649475
Epoch: 21, Loss: 0.18715719878673553
Epoch: 22, Loss: 0.18351857364177704
Epoch: 23, Loss: 0.1801169365644455
Epoch: 24, Loss: 0.17692844569683075
Epoch: 25, Loss: 0.1739324927330017


In [61]:
model.linear.bias

Parameter containing:
tensor([-0.2621], requires_grad=True)

In [62]:
model.linear.weight

Parameter containing:
tensor([[ 0.3658,  0.2841,  0.2838,  0.1097,  0.2561,  0.1760,  0.0952,  0.2743,
          0.0860, -0.1293,  0.3028, -0.0168,  0.0571,  0.2499, -0.0583, -0.0528,
          0.1164, -0.0062, -0.0562, -0.1528,  0.2174,  0.1330,  0.1442,  0.1799,
          0.0993,  0.1524,  0.3272,  0.2894,  0.0288,  0.1287]],
       requires_grad=True)

### Evaluation

In [64]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor.float())
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.573253333568573
