<a href="https://colab.research.google.com/github/iamisha/Pytorch/blob/day11/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# create a model

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    # for single neuron without hidden layer
    # self.linear = nn.Linear(num_featrues, 1)
    # self.sigmoid = nn.Sigmoid()

    # with hidden layer
    self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
    )

  def forward(self, features):

    # for single neuron without hidden layer
    # out = self.linear(features)
    # out = self.sigmoid(out)

    # with hidden layer
    out = self.network(features)

    return out

In [22]:
# create dataset
features = torch.rand(10,6)

# create model object
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4952],
        [0.5242],
        [0.4974],
        [0.5259],
        [0.5027],
        [0.4989],
        [0.4714],
        [0.5194],
        [0.4822],
        [0.4717]], grad_fn=<SigmoidBackward0>)

In [16]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[-0.0378,  0.0269,  0.2684,  0.2817,  0.0256, -0.1687],
        [ 0.1654, -0.2858,  0.1818,  0.3864, -0.1215,  0.3882],
        [ 0.3066, -0.1077, -0.0591,  0.1045, -0.3437, -0.2998]],
       requires_grad=True)

In [17]:
# show model bias
model.linear1.bias

Parameter containing:
tensor([ 0.2796,  0.2539, -0.0115], requires_grad=True)

In [18]:
!pip install torchinfo

In [19]:
from torchinfo import summary

summary(model, input_size=(10,6))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   21
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 25
Trainable params: 25
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00