<a href="https://colab.research.google.com/github/iamisha/Pytorch/blob/day3/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Day-2



In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'You are using: ',torch.cuda.get_device_name(0))
else:
  print('GPU is not available')

GPU is available
You are using:  Tesla T4


## Creating Tenosr

In [3]:
# Using empty
a = torch.empty(2,3)
torch.empty(3,2)

tensor([[0.0000e+00, 0.0000e+00],
        [4.2039e-45, 0.0000e+00],
        [4.2039e-45, 7.0065e-45]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Using rand
torch.rand(2,3)

tensor([[0.1491, 0.4223, 0.5970],
        [0.4097, 0.6678, 0.0939]])

In [8]:
# Use of seed
torch.rand(2,3) # it gets random values each time you run

tensor([[0.5460, 0.2025, 0.3000],
        [0.3204, 0.6478, 0.8094]])

In [9]:
# manual seed gives same values of rand each time you run the cell
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Using tensor
torch.tensor([(1,2),[3,4]])

tensor([[1, 2],
        [3, 4]])

In [12]:
# Other ways

print(f'using arange: ', torch.arange(0,10,2))

print(f'using linspace: ', torch.linspace(0,10,5))

print(f'Using eye: ', torch.eye(5))


print(f'Using full: ', torch.full((3,2),3))


using arange:  tensor([0, 2, 4, 6, 8])
using linspace:  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full:  tensor([[3, 3],
        [3, 3],
        [3, 3]])


# Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [17]:
x.shape

torch.Size([2, 3])

In [21]:
# create the tensors of same size
torch.empty_like(x)

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [36]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [26]:
# assign data type
torch.tensor([1.0,2.0,3.0],  dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3],  dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
# using to() method
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**               | **Dtype**           | **Description**                                                                 |
|----------------------------|---------------------|---------------------------------------------------------------------------------|
| 32-bit Floating Point       | `torch.float32`     | Standard floating-point type used for most deep learning tasks.                |
| 64-bit Floating Point       | `torch.float64`     | Double-precision floating point. Higher precision, more memory.                |
| 16-bit Floating Point       | `torch.float16`     | Half-precision float. Reduces memory/computation in mixed-precision training.  |
| BFloat16                    | `torch.bfloat16`    | Reduced precision float for mixed-precision, common on TPUs.                   |
| 8-bit Floating Point        | `torch.float8`      | Ultra-low-precision float. Experimental, for extreme memory limits.            |
| 8-bit Integer               | `torch.int8`        | Signed 8-bit integer. Used in quantized inference models.                      |
| 16-bit Integer              | `torch.int16`       | Signed 16-bit integer. Intermediate numerical precision.                       |
| 32-bit Integer              | `torch.int32`       | Standard integer for indexing/general numerical tasks.                         |
| 64-bit Integer              | `torch.int64`       | Long integer. Suitable for large numbers/indices.                              |
| 8-bit Unsigned Integer      | `torch.uint8`       | Unsigned 8-bit. Common for image pixel values (0–255).                         |
| Boolean                     | `torch.bool`        | Boolean type (`True`/`False`). Used in masking and logical ops.                |
| Complex 64                  | `torch.complex64`   | Complex type with 32-bit real & imaginary parts. Used in scientific computing. |
| Complex 128                 | `torch.complex128`  | Complex type with 64-bit real & imaginary parts. High precision.               |
| Quantized Integer           | `torch.qint8`       | Quantized signed 8-bit integer. Efficient for inference.                       |
| Quantized Unsigned Integer  | `torch.quint8`      | Quantized unsigned 8-bit. Used in image-related quantized models.              |

# Mathematical Operation


In [47]:
y = torch.rand(2,2)
y

tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])

In [48]:
# Scalar operations

# addition
y + 2

# substraction
y - 2

# division
y/2

# int division
(50 * y)//2

# modular division
y % 2

# power
y ** 2

tensor([[0.0318, 0.6787],
        [0.3089, 0.9546]])

# Elementwise Operation

In [50]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])
tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])


In [56]:
# add
a + b

# substract
a - b

# mul
a * b

# div
a / b

# mod
a % b

# power
a ** b

tensor([[0.9697, 0.8876, 0.5613],
        [0.9406, 0.9709, 0.1818]])

## Single Tensor Elementwise Operation

In [59]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [61]:
# abs
torch.abs(c)

# neg
torch.neg(c)

tensor([-1,  2, -3,  4])

In [62]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [67]:
# round
torch.round(d)

# ceil
torch.ceil(d)

# floor
torch.floor(d)

# clamp
torch.clamp(d, min=3, max=4)

tensor([3.0000, 3.0000, 3.7000, 4.0000])

## Reduction Operation

In [75]:
e = torch.randint(size =(2,3), low=0, high=20, dtype=torch.float32)
e

tensor([[ 8.,  3.,  3.],
        [ 5., 10., 16.]])

In [77]:
# sum
torch.sum(e)

# sum columnwise
torch.sum(e, dim=0)

# sum rowwise
torch.sum(e, dim=1)

tensor([14., 31.])

In [79]:
# mean
torch.mean(e)

# mean, columnwise
torch.mean(e, dim=0)

# mean, rowwise
torch.mean(e, dim=1)

tensor([ 4.6667, 10.3333])

In [80]:
# median
torch.median(e)

tensor(5.)

In [82]:
# min and max
torch.min(e)
torch.max(e)

tensor(16.)

In [83]:
# product
torch.prod(e)

tensor(57600.)

In [84]:
# standard deviation
torch.std(e)

tensor(5.0100)

In [85]:
# variance
torch.var(e)

tensor(25.1000)

In [86]:
# argmax
torch.argmax(e)

tensor(5)

In [87]:
# argmin
torch.argmin(e)

tensor(1)

## Matrix Operation



In [89]:
f = torch.randint(size =(2,3), low=0, high=20)
g = torch.randint(size =(3,2), low=0, high=20)

print(f)
print(g)

tensor([[14,  0,  8],
        [14, 17,  2]])
tensor([[13,  8],
        [ 5,  6],
        [ 2,  9]])


In [90]:
# matrix multiplication
torch.matmul(f,g)

tensor([[198, 184],
        [271, 232]])

In [93]:
# dot product

vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

torch.dot(vec1, vec2)



tensor(11)

In [96]:
f

tensor([[14,  0,  8],
        [14, 17,  2]])

In [97]:
# transpose
torch.transpose(f,0,1)

tensor([[14, 14],
        [ 0, 17],
        [ 8,  2]])

In [102]:
h = torch.randint(size = (3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 4., 5.],
        [6., 9., 2.],
        [3., 1., 0.]])

In [103]:
# determinant
torch.det(h)

tensor(-83.)

In [104]:
# inverse
torch.inverse(h)

tensor([[ 0.0241, -0.0602,  0.4458],
        [-0.0723,  0.1807, -0.3373],
        [ 0.2530, -0.1325,  0.1807]])

## Comparision Operation

In [105]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[2, 1, 2],
        [7, 9, 2]])
tensor([[4, 6, 6],
        [8, 4, 9]])


In [111]:
# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## Special Functions

In [ ]:
# start from here...