<a href="https://colab.research.google.com/github/iamisha/Pytorch/blob/day4/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### D-4



In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'You are using: ',torch.cuda.get_device_name(0))
else:
  print('GPU is not available')

GPU is available
You are using:  Tesla T4


## Creating Tenosr

In [ ]:
# Using empty
a = torch.empty(2,3)
torch.empty(3,2)

tensor([[1.1479e-41, 0.0000e+00],
        [5.8294e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Using rand
torch.rand(2,3)

tensor([[0.5650, 0.2906, 0.2343],
        [0.0819, 0.0406, 0.0683]])

In [ ]:
# Use of seed
torch.rand(2,3) # it gets random values each time you run

tensor([[0.7393, 0.9342, 0.6530],
        [0.3782, 0.8819, 0.6616]])

In [ ]:
# manual seed gives same values of rand each time you run the cell
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Using tensor
torch.tensor([(1,2),[3,4]])

tensor([[1, 2],
        [3, 4]])

In [ ]:
# Other ways

print(f'using arange: ', torch.arange(0,10,2))

print(f'using linspace: ', torch.linspace(0,10,5))

print(f'Using eye: ', torch.eye(5))


print(f'Using full: ', torch.full((3,2),3))


using arange:  tensor([0, 2, 4, 6, 8])
using linspace:  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full:  tensor([[3, 3],
        [3, 3],
        [3, 3]])


# Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# create the tensors of same size
torch.empty_like(x)

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],  dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],  dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to() method
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**               | **Dtype**           | **Description**                                                                 |
|----------------------------|---------------------|---------------------------------------------------------------------------------|
| 32-bit Floating Point       | `torch.float32`     | Standard floating-point type used for most deep learning tasks.                |
| 64-bit Floating Point       | `torch.float64`     | Double-precision floating point. Higher precision, more memory.                |
| 16-bit Floating Point       | `torch.float16`     | Half-precision float. Reduces memory/computation in mixed-precision training.  |
| BFloat16                    | `torch.bfloat16`    | Reduced precision float for mixed-precision, common on TPUs.                   |
| 8-bit Floating Point        | `torch.float8`      | Ultra-low-precision float. Experimental, for extreme memory limits.            |
| 8-bit Integer               | `torch.int8`        | Signed 8-bit integer. Used in quantized inference models.                      |
| 16-bit Integer              | `torch.int16`       | Signed 16-bit integer. Intermediate numerical precision.                       |
| 32-bit Integer              | `torch.int32`       | Standard integer for indexing/general numerical tasks.                         |
| 64-bit Integer              | `torch.int64`       | Long integer. Suitable for large numbers/indices.                              |
| 8-bit Unsigned Integer      | `torch.uint8`       | Unsigned 8-bit. Common for image pixel values (0–255).                         |
| Boolean                     | `torch.bool`        | Boolean type (`True`/`False`). Used in masking and logical ops.                |
| Complex 64                  | `torch.complex64`   | Complex type with 32-bit real & imaginary parts. Used in scientific computing. |
| Complex 128                 | `torch.complex128`  | Complex type with 64-bit real & imaginary parts. High precision.               |
| Quantized Integer           | `torch.qint8`       | Quantized signed 8-bit integer. Efficient for inference.                       |
| Quantized Unsigned Integer  | `torch.quint8`      | Quantized unsigned 8-bit. Used in image-related quantized models.              |

# Mathematical Operation


In [ ]:
y = torch.rand(2,2)
y

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# Scalar operations

# addition
y + 2

# substraction
y - 2

# division
y/2

# int division
(50 * y)//2

# modular division
y % 2

# power
y ** 2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# Elementwise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
# add
a + b

# substract
a - b

# mul
a * b

# div
a / b

# mod
a % b

# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

## Single Tensor Elementwise Operation

In [ ]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
# abs
torch.abs(c)

# neg
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

# ceil
torch.ceil(d)

# floor
torch.floor(d)

# clamp
torch.clamp(d, min=3, max=4)

tensor([3.0000, 3.0000, 3.7000, 4.0000])

## Reduction Operation

In [ ]:
e = torch.randint(size =(2,3), low=0, high=20, dtype=torch.float32)
e

tensor([[18., 10.,  7.],
        [ 0.,  0., 19.]])

In [ ]:
# sum
torch.sum(e)

# sum columnwise
torch.sum(e, dim=0)

# sum rowwise
torch.sum(e, dim=1)

tensor([35., 19.])

In [ ]:
# mean
torch.mean(e)

# mean, columnwise
torch.mean(e, dim=0)

# mean, rowwise
torch.mean(e, dim=1)

tensor([11.6667,  6.3333])

In [ ]:
# median
torch.median(e)

tensor(7.)

In [ ]:
# min and max
torch.min(e)
torch.max(e)

tensor(19.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(8.3427)

In [ ]:
# variance
torch.var(e)

tensor(69.6000)

In [ ]:
# argmax
torch.argmax(e)

tensor(5)

In [ ]:
# argmin
torch.argmin(e)

tensor(3)

## Matrix Operation



In [ ]:
f = torch.randint(size =(2,3), low=0, high=20)
g = torch.randint(size =(3,2), low=0, high=20)

print(f)
print(g)

tensor([[ 5, 17, 13],
        [19,  4,  0]])
tensor([[15,  7],
        [15, 19],
        [ 9,  7]])


In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[447, 449],
        [345, 209]])

In [ ]:
# dot product

vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

torch.dot(vec1, vec2)



tensor(11)

In [ ]:
f

tensor([[ 5, 17, 13],
        [19,  4,  0]])

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[ 5, 19],
        [17,  4],
        [13,  0]])

In [ ]:
h = torch.randint(size = (3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(-110.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

## Comparision Operation

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [ ]:
# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## Special Functions

In [ ]:
k = torch.randint(size = (2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [ ]:
# log
torch.log(k)


tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [ ]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

## Inplace Operations


---

In PyTorch, an in-place operation directly modifies the content of a tensor without creating a new one. In-place operations are typically indicated by a trailing underscore (_) in the method name (e.g., add_(), relu_(), etc.).



In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [ ]:
m.add_(n) # m + n stores the result in a new address, occupying more memory, so we use m.add_(n) instead

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [ ]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [ ]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
torch.relu(m) # creates a new tensor and leaves m unchanged

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [ ]:
m.relu_() # modifies m in place, replacing negative values with zero directly in m.

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

## Copying a Tensor

In [ ]:
o = torch.rand(2,3)
o

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
p = o # not desirable

In [ ]:
p

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
o[0][0] = 0 # change the original matrix
o

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
p # the copied matrix has also changed

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
id(o)

135840601094480

In [ ]:
id(p) # pointing to the same id as original matrix

135840601094480

In [ ]:
# Using clone() function to copy a tensor
p = o.clone() # tensor is formed completely at new location

In [ ]:
o

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
p

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
# change original tensor
o[0][0] = 8

In [ ]:
o

tensor([[8.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
p # p remains unchanged

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
id(o)

135840601094480

In [ ]:
id(p) # tensor is formed completely at new location

135840599302672

# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda') # assigning gpu to device variable

In [ ]:
# creating a new tensor on GPU

torch.rand((2,3), device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [ ]:
# moving an existing tensor a to GPU
q = a.to(device)
q

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]], device='cuda:0')

In [ ]:
q + 2 # all operations perfomed will be performed in gpu

tensor([[2.9969, 2.7565, 2.2239],
        [2.3023, 2.1784, 2.8238]], device='cuda:0')

# Reshaping Tensors

In [ ]:
r = torch.ones(4,4)
r

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
r.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten gives one dimensional tensor
r.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
s = torch.rand(2,3,4) # s is at '0', 3 is at '1' and 4 is at '2'.
s

tensor([[[0.4907, 0.2130, 0.4603, 0.1386],
         [0.0277, 0.5662, 0.3503, 0.6555],
         [0.7667, 0.2269, 0.7555, 0.6458]],

        [[0.3673, 0.1770, 0.2966, 0.9925],
         [0.2103, 0.1292, 0.1719, 0.9127],
         [0.6818, 0.1953, 0.9991, 0.1133]]])

In [ ]:
# permute
s.permute(2,0,1)

tensor([[[0.4907, 0.0277, 0.7667],
         [0.3673, 0.2103, 0.6818]],

        [[0.2130, 0.5662, 0.2269],
         [0.1770, 0.1292, 0.1953]],

        [[0.4603, 0.3503, 0.7555],
         [0.2966, 0.1719, 0.9991]],

        [[0.1386, 0.6555, 0.6458],
         [0.9925, 0.9127, 0.1133]]])

In [ ]:
s.permute(2,0,1).shape

torch.Size([4, 2, 3])

The .unsqueeze() function in PyTorch adds a dimension of size 1 at the specified position in the tensor's shape.

This is commonly done to add a batch dimension. Many models expect input in the shape (batch_size, height, width, channels) (or sometimes (batch_size, channels, height, width) depending on the framework), even if you're passing just one image.

In [ ]:
# unsqeeze

# typical image size
t = torch.rand(226,226,3)

t.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze

u = torch.rand(1,20)
u

tensor([[0.6867, 0.4318, 0.0188, 0.1314, 0.3670, 0.0546, 0.9839, 0.6308, 0.6006,
         0.0024, 0.4524, 0.0113, 0.7392, 0.6449, 0.4497, 0.7156, 0.5628, 0.8409,
         0.0865, 0.0522]])

squeeze() is the opposite of unsqueeze() — it removes dimensions of size 1 from a tensor's shape.

In [ ]:
u.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
v = torch.tensor([1,2,3])
v

tensor([1, 2, 3])

In [ ]:
w = v.numpy() # converting tensor to numpy
w

array([1, 2, 3])

In [ ]:
type(w)

numpy.ndarray

In [ ]:
x = np.array([4,5,6]) # creating a numpy array
x

array([4, 5, 6])

In [ ]:
torch.from_numpy(x) # convering numpy array to pytorch tensor

tensor([4, 5, 6])