<a href="https://colab.research.google.com/github/iamisha/Pytorch/blob/day2/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Day-2



In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'You are using: ',torch.cuda.get_device_name(0))
else:
  print('GPU is not available')

GPU is available
You are using:  Tesla T4


## Creating Tenosr

In [9]:
# Using empty
a = torch.empty(2,3)
torch.empty(3,2)

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.5483e-41]])

In [10]:
# check type
type(a)

torch.Tensor

In [11]:
# Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# Using rand
torch.rand(2,3)

tensor([[0.6606, 0.2342, 0.3843],
        [0.6359, 0.0668, 0.6250]])

In [14]:
# Use of seed
torch.rand(2,3) # it gets random values each time you run

tensor([[0.5628, 0.5056, 0.1578],
        [0.9809, 0.2006, 0.6173]])

In [15]:
# manual seed gives same values of rand each time you run the cell
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
# Using tensor
torch.tensor([(1,2),[3,4]])

tensor([[1, 2],
        [3, 4]])

In [32]:
# Other ways

print(f'using arange: ', torch.arange(0,10,2))

print(f'using linspace: ', torch.linspace(0,10,5))

print(f'Using eye: ', torch.eye(5))


print(f'Using full: ', torch.full((3,2),3))


using arange:  tensor([0, 2, 4, 6, 8])
using linspace:  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full:  tensor([[3, 3],
        [3, 3],
        [3, 3]])


# Tensor Shapes

In [ ]:
# Start from here...